name: 📜 CDL Task
description: CDL Main Task / Story Template
labels: ["task"]
#assignees:
body:
  - type: markdown
    attributes:
      value: |
        This is template for user stories and engineering tasks.
  - type: textarea
    id: request_body
    attributes:
      label: (1) Jobs to Be Done
      description: |
       💡 Tip: use "agile user story structure".  Add any attachments or images you need by dragging them onto this box.
      placeholder: |
       examples:
       - As a _____ I want to _____ so I can _____
       - Please move the language control to the leftmost position (see screenshot)
       - Please get an extract of the log files for the batch system between 2023-12-24 and 2023-12-25 UTC
    validations:
      required: true
  - type: textarea
    id: request_acceptance
    attributes:
      label: (2) Acceptance Criteria 
      description: How do we know we have succeeded? Outcomes, Measures & Metrics.
      placeholder: |
       examples:
       - All menus in Japanese by default
       - System processes a file of 10,000 records in <10 mins.
       - Need to pass UI tests
      value: |
        - All menus in Japanese by default
        - Need to run and pass: [UI tests](https://github.com/C-Datalab/CDL-Automated-Tests/actions/workflows/ManualPublishToTestmo.yml)
    render: markdown
  validations:
    required: false
  - type: markdown
    attributes:
      value: |
       [UI tests](https://github.com/C-Datalab/CDL-Automated-Tests/actions/workflows/ManualPublishToTestmo.yml)
       > **:bulb: Don't forget to set Size, % Complete, Assignee and Other labels on the Right pane 👉**
