name: 📕 CDL Epic
description: CDL Epic template
title: "[CDL EPIC]: "
labels: ["epic"]
#assignees:
body:
  - type: markdown
    attributes:
      value: |
        This is template for epics (high-level tasks that contain other tasks).
  - type: textarea
    id: request_body
    attributes:
      label: Brief description
      placeholder: |
        Brief description of the topic.
    validations:
      required: true
  - type: textarea
    id: sub_tasks
    attributes:
      label: child_issues
      description: |
       💡 Create tasks or paste URLs of other issues to link them, or create issues from a task in the list.
      value: |
        ```[tasklist]
        - [ ] subtask_sample
        ```
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
       > **:bulb: Don't forget to set Project, Assignee and Other labels on the Right pane 👉**
