name: 🐞 CDL Bug Report
description: Bug Report
title: "[🐞 CDL BUG]: "
labels: ["bug"]
#assignees:
body:
  - type: markdown
    attributes:
      value: |
        Please provide as much information as possible.
  - type: textarea
    id: issue-description
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: What happened where?
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      multiple: false
      options:
        - Sev 1 - 🔥 Show-stopper
        - Sev 2 - 🛑 System Stops
        - Sev 3 - 👎 Significant problem but system keeps running
        - Sev 4 - 🫤 Minor, can work around
        - Sev 5 - 🎨 Cosmetic = Look & Feel
        - Sev 6 - ❓ Question
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - n/a
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge       
  - type: dropdown
    id: environments
    attributes:
      label: What environment(s) does this apply to?
      multiple: true
      options:
        - Production
        - Dev
        - Design
  - type: dropdown
    id: Platform
    attributes:
      label: Platforms
      multiple: true
      options:
        - 🖥️ Desktop
        - 📱 Mobile
      default: 0
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
