name: 📕 CDL Epic
description: CDL Epic template
title: "[CDL EPIC]: "
labels: ["epic"]
#assignees:
body:
  - type: markdown
    attributes:
      value: |
        This is template for epics (high-level tasks that contain other tasks).
  - type: textarea
    id: request_body
    attributes:
      label: Brief description
      placeholder: |
        Brief description of the topic.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
       > **:bulb: Don't forget to set Project, Assignee and Other labels on the Right pane 👉**
